fix(components/atom/label): Changed demo label and src
SUI-Components/sui-components pull request #1821
Opened 2021-10-13 14:29 UTC by delalama

Added bottom margin on label and optional text on demo

ISSUES CLOSED: #1752

### Types of changes
Optional text from * to (Optional)

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Only
- [ ] Refactor

### Description, Motivation and Context
Uppercased inital label name as requirements
Added bottom margin to label

### Screenshots - Animations
![Selection_005](https://user-images.githubusercontent.com/20232667/137153518-b017a862-cc3b-4fde-a8ae-2c465714677f.png)
![uppercased label name](https://user-images.githubusercontent.com/20232667/137153523-bc9d1e79-d83c-49d0-afa2-0ca2e63451ba.png)

2021-10-13 14:34 UTC, delalama commented
Hi, i can't understand this CI / build (pull_request)  problem, can u explain please ?

2021-10-13 16:08 UTC, andresin87 commented
> Hi, i can't understand this CI / build (pull_request) problem, can u explain please ?

This process is not currently forked for incoming forked branches. Sorry

2021-10-13 16:17 UTC, andresin87 requested changes

2021-10-13 16:17 UTC, andresin87 commented on components/atom/label/src/index.scss
> +  margin-bottom: 4px;
Why u need this? It will produce a major. Plz, remove it.

To add the AtomInput:

- go to `components/atom/label/demo`

- create a package.jsno if it does not exist:
`npm init`
the name of the demo package should be `@s-ui/react-atom-label-demo`

- install it `npm i -E @s-ui/react-atom-input@5`

- add its scss to the demo scss
```scss
// components/atom/label/demo/index.scss
@import '~@s-ui/theme/lib/index';
@import '~@s-ui/react-atom-input/lib/index';

// Add your magic here
```

- import it in the index.js
```js
import AtomInput from '@s-ui/react-atom-input'
```

2021-10-13 16:18 UTC, andresin87 commented on components/atom/label/src/index.scss
> +  margin-bottom: 4px;
Thanks in advance 4 your collaboration 👏

2021-10-13 16:27 UTC, delalama commented on components/atom/label/src/index.scss
> +  margin-bottom: 4px;
understood, that´s my fault, i imported it without previous compile, thanks.

Don´t know how to vertical separate from the input text withou the margin-bottom line...... it was added to follow the guidelines of the issue

2021-10-15 07:22 UTC, andresin87 commented on components/atom/label/src/index.scss
> +  margin-bottom: 4px;
@delalama are you going to update the changes or i'll take it

2021-10-15 07:57 UTC, delalama commented on components/atom/label/src/index.scss
> +  margin-bottom: 4px;
Hi Andres, done
![atomLabel](https://user-images.githubusercontent.com/20232667/137452602-ecdcd9ab-ffba-4ed0-ac04-67e51c969c48.png)

2021-10-15 08:10 UTC, delalama commented on components/atom/label/src/index.scss
> +  margin-bottom: 4px;
i've done a second commit to delete the duplicated import.

alignment is broken when there is a shorter label message, when you accept the PR i can work on it.

2021-10-16 09:25 UTC, andresin87 approved these changes

2021-10-16 09:31 UTC, andresin87 approved these changes

2021-10-16 09:31 UTC, merged